export const data = JSON.parse("{\"key\":\"v-b8911b22\",\"path\":\"/Program/%E5%89%8D%E7%AB%AF/Vue.js/%E7%9F%A5%E8%AF%86%E7%82%B9/%E5%9F%BA%E7%A1%80%E8%AF%AD%E6%B3%95/%E8%AE%A1%E7%AE%97%E5%B1%9E%E6%80%A7%EF%BC%8C%E5%86%85%E5%AE%B9%E5%88%86%E5%8F%91%EF%BC%8C%E8%87%AA%E5%AE%9A%E4%B9%89%E4%BA%8B%E4%BB%B6%EF%BC%8C%E7%9B%91%E5%90%AC%E5%99%A8.html\",\"title\":\"计算属性，内容分发，自定义事件，监听器\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"计算属性，内容分发，自定义事件，监听器\",\"order\":50,\"description\":\"计算属性 模板内的表达式非常便利，但是设计它们的初衷是用于简单运算的。在模板中放入太多的逻辑会让模板过重且难以维护。 ```html {{ message.split('').reverse().join('') }} ``` 在这个地方，模板不再是简单的声明式逻辑。你必须看一段时间才能意识到，这里是想要显示变量 message 的翻转字符串。当你想要...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/testdoc/Program/%E5%89%8D%E7%AB%AF/Vue.js/%E7%9F%A5%E8%AF%86%E7%82%B9/%E5%9F%BA%E7%A1%80%E8%AF%AD%E6%B3%95/%E8%AE%A1%E7%AE%97%E5%B1%9E%E6%80%A7%EF%BC%8C%E5%86%85%E5%AE%B9%E5%88%86%E5%8F%91%EF%BC%8C%E8%87%AA%E5%AE%9A%E4%B9%89%E4%BA%8B%E4%BB%B6%EF%BC%8C%E7%9B%91%E5%90%AC%E5%99%A8.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"Mahe666\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"计算属性，内容分发，自定义事件，监听器\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"计算属性 模板内的表达式非常便利，但是设计它们的初衷是用于简单运算的。在模板中放入太多的逻辑会让模板过重且难以维护。 ```html {{ message.split('').reverse().join('') }} ``` 在这个地方，模板不再是简单的声明式逻辑。你必须看一段时间才能意识到，这里是想要显示变量 message 的翻转字符串。当你想要...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"Mahe666\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"计算属性，内容分发，自定义事件，监听器\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"Mahe666\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"计算属性\",\"slug\":\"计算属性\",\"link\":\"#计算属性\",\"children\":[{\"level\":3,\"title\":\"计算属性 和 方法\",\"slug\":\"计算属性-和-方法\",\"link\":\"#计算属性-和-方法\",\"children\":[]},{\"level\":3,\"title\":\"计算属性 和 监听器\",\"slug\":\"计算属性-和-监听器\",\"link\":\"#计算属性-和-监听器\",\"children\":[]}]},{\"level\":2,\"title\":\"slot插槽\",\"slug\":\"slot插槽\",\"link\":\"#slot插槽\",\"children\":[]},{\"level\":2,\"title\":\"内容分发\",\"slug\":\"内容分发\",\"link\":\"#内容分发\",\"children\":[]},{\"level\":2,\"title\":\"监听器\",\"slug\":\"监听器\",\"link\":\"#监听器\",\"children\":[{\"level\":3,\"title\":\"监听基本数据类型\",\"slug\":\"监听基本数据类型\",\"link\":\"#监听基本数据类型\",\"children\":[]},{\"level\":3,\"title\":\"深度监听对象类型\",\"slug\":\"深度监听对象类型\",\"link\":\"#深度监听对象类型\",\"children\":[]},{\"level\":3,\"title\":\"在vue中watch和created哪个先执行？\",\"slug\":\"在vue中watch和created哪个先执行\",\"link\":\"#在vue中watch和created哪个先执行\",\"children\":[]}]}],\"readingTime\":{\"minutes\":6.56,\"words\":1967},\"filePathRelative\":\"Program/前端/Vue.js/知识点/基础语法/计算属性，内容分发，自定义事件，监听器.md\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
