export const data = JSON.parse("{\"key\":\"v-1d6f9f2c\",\"path\":\"/Program/%E5%90%8E%E7%AB%AF/Java/SpringBoot/%E9%80%9A%E7%94%A8%E5%BC%80%E5%8F%91%E7%AC%94%E8%AE%B0.html\",\"title\":\"通用开发笔记\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"通用开发笔记\",\"order\":20,\"description\":\"配置端口和项目前缀 ```yaml server: port: 8080 servlet: context-path: /mahe666 ``` yaml给实体类赋值的几种方式 类模板获取默认值的三种方式 ```java Data AllArgsConstructor NoArgsConstructor //注册为组件 Component public...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://mahe666.github.io/testdoc/Program/%E5%90%8E%E7%AB%AF/Java/SpringBoot/%E9%80%9A%E7%94%A8%E5%BC%80%E5%8F%91%E7%AC%94%E8%AE%B0.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"Mahe666\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"通用开发笔记\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"配置端口和项目前缀 ```yaml server: port: 8080 servlet: context-path: /mahe666 ``` yaml给实体类赋值的几种方式 类模板获取默认值的三种方式 ```java Data AllArgsConstructor NoArgsConstructor //注册为组件 Component public...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"Mahe666\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"通用开发笔记\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"Mahe666\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"配置端口和项目前缀\",\"slug\":\"配置端口和项目前缀\",\"link\":\"#配置端口和项目前缀\",\"children\":[]},{\"level\":2,\"title\":\"yaml给实体类赋值的几种方式\",\"slug\":\"yaml给实体类赋值的几种方式\",\"link\":\"#yaml给实体类赋值的几种方式\",\"children\":[{\"level\":3,\"title\":\"SpringBoot配置文件示例\",\"slug\":\"springboot配置文件示例\",\"link\":\"#springboot配置文件示例\",\"children\":[]}]},{\"level\":2,\"title\":\"异步任务，邮件任务，定时任务\",\"slug\":\"异步任务-邮件任务-定时任务\",\"link\":\"#异步任务-邮件任务-定时任务\",\"children\":[{\"level\":3,\"title\":\"异步任务\",\"slug\":\"异步任务\",\"link\":\"#异步任务\",\"children\":[]},{\"level\":3,\"title\":\"邮件任务\",\"slug\":\"邮件任务\",\"link\":\"#邮件任务\",\"children\":[]},{\"level\":3,\"title\":\"定时任务\",\"slug\":\"定时任务\",\"link\":\"#定时任务\",\"children\":[]}]},{\"level\":2,\"title\":\"项目启动后执行方法\",\"slug\":\"项目启动后执行方法\",\"link\":\"#项目启动后执行方法\",\"children\":[]},{\"level\":2,\"title\":\"配置响应结构\",\"slug\":\"配置响应结构\",\"link\":\"#配置响应结构\",\"children\":[]},{\"level\":2,\"title\":\"SpringBoot整合Mybatis\",\"slug\":\"springboot整合mybatis\",\"link\":\"#springboot整合mybatis\",\"children\":[{\"level\":3,\"title\":\"整合Druid数据源\",\"slug\":\"整合druid数据源\",\"link\":\"#整合druid数据源\",\"children\":[]}]},{\"level\":2,\"title\":\"声明式事务\",\"slug\":\"声明式事务\",\"link\":\"#声明式事务\",\"children\":[]}],\"filePathRelative\":\"Program/后端/Java/SpringBoot/通用开发笔记.md\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
