export const data = JSON.parse("{\"key\":\"v-d65450c6\",\"path\":\"/Program/%E5%90%8E%E7%AB%AF/Java/SpringBoot/%E9%A1%B9%E7%9B%AE%E9%94%99%E8%AF%AF%E7%AC%94%E8%AE%B0.html\",\"title\":\"项目错误笔记\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"项目错误笔记\",\"order\":70,\"description\":\"No primary or default constructor found for interface javax.servlet.http.ServletContext controller层 ServletContext 参数和初始化项目时引用的 ServletContext 冲突 建议在controller层使用session或者reques...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://mahe666.github.io/doc/Program/%E5%90%8E%E7%AB%AF/Java/SpringBoot/%E9%A1%B9%E7%9B%AE%E9%94%99%E8%AF%AF%E7%AC%94%E8%AE%B0.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"Mahe666\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"项目错误笔记\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"No primary or default constructor found for interface javax.servlet.http.ServletContext controller层 ServletContext 参数和初始化项目时引用的 ServletContext 冲突 建议在controller层使用session或者reques...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"Mahe666\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"项目错误笔记\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"Mahe666\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"No primary or default constructor found for interface javax.servlet.http.ServletContext\",\"slug\":\"no-primary-or-default-constructor-found-for-interface-javax-servlet-http-servletcontext\",\"link\":\"#no-primary-or-default-constructor-found-for-interface-javax-servlet-http-servletcontext\",\"children\":[]},{\"level\":2,\"title\":\"Unable to find a @SpringBootConfiguration, you need to use @ContextConfiguration\",\"slug\":\"unable-to-find-a-springbootconfiguration-you-need-to-use-contextconfiguration\",\"link\":\"#unable-to-find-a-springbootconfiguration-you-need-to-use-contextconfiguration\",\"children\":[]},{\"level\":2,\"title\":\"400\",\"slug\":\"_400\",\"link\":\"#_400\",\"children\":[]},{\"level\":2,\"title\":\"Unexpected character ('o' (code 111)): was expecting double-quote to start field name.\",\"slug\":\"unexpected-character-o-code-111-was-expecting-double-quote-to-start-field-name\",\"link\":\"#unexpected-character-o-code-111-was-expecting-double-quote-to-start-field-name\",\"children\":[]},{\"level\":2,\"title\":\"Not allowed to load local resource\",\"slug\":\"not-allowed-to-load-local-resource\",\"link\":\"#not-allowed-to-load-local-resource\",\"children\":[]}],\"filePathRelative\":\"Program/后端/Java/SpringBoot/项目错误笔记.md\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
