export const data = JSON.parse("{\"key\":\"v-668b7d2e\",\"path\":\"/Program/%E5%90%8E%E7%AB%AF/Java/JavaSE%E5%9F%BA%E7%A1%80/%E9%9D%A2%E5%90%91%E5%AF%B9%E8%B1%A1%E6%A6%82%E5%BF%B5/%E5%9E%83%E5%9C%BE%E5%9B%9E%E6%94%B6%E6%9C%BA%E5%88%B6.html\",\"title\":\"垃圾回收机制\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"垃圾回收机制\",\"order\":40,\"description\":\"垃圾回收机制（Garbage Collection） Java引入了垃圾回收机制，令C++程序员最头疼的内存管理问题得以解决。Java程序员可以将更多的精力放到业务逻辑上，而不是内存管理上，提高了开发效率 在C++中，程序员不仅需要开发业务代码，还要关注内存管理问题。如果某一个对象不再使用了，则需要进行回收，否则程序很有可能因为这个对象没有被回收而导致...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://mahe666.github.io/doc/Program/%E5%90%8E%E7%AB%AF/Java/JavaSE%E5%9F%BA%E7%A1%80/%E9%9D%A2%E5%90%91%E5%AF%B9%E8%B1%A1%E6%A6%82%E5%BF%B5/%E5%9E%83%E5%9C%BE%E5%9B%9E%E6%94%B6%E6%9C%BA%E5%88%B6.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"Mahe666\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"垃圾回收机制\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"垃圾回收机制（Garbage Collection） Java引入了垃圾回收机制，令C++程序员最头疼的内存管理问题得以解决。Java程序员可以将更多的精力放到业务逻辑上，而不是内存管理上，提高了开发效率 在C++中，程序员不仅需要开发业务代码，还要关注内存管理问题。如果某一个对象不再使用了，则需要进行回收，否则程序很有可能因为这个对象没有被回收而导致...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"Mahe666\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"垃圾回收机制\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"Mahe666\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"内存管理及垃圾回收过程\",\"slug\":\"内存管理及垃圾回收过程\",\"link\":\"#内存管理及垃圾回收过程\",\"children\":[{\"level\":3,\"title\":\"内存管理\",\"slug\":\"内存管理\",\"link\":\"#内存管理\",\"children\":[]},{\"level\":3,\"title\":\"垃圾回收过程\",\"slug\":\"垃圾回收过程\",\"link\":\"#垃圾回收过程\",\"children\":[]}]},{\"level\":2,\"title\":\"垃圾回收相关算法\",\"slug\":\"垃圾回收相关算法\",\"link\":\"#垃圾回收相关算法\",\"children\":[{\"level\":3,\"title\":\"引用计数法\",\"slug\":\"引用计数法\",\"link\":\"#引用计数法\",\"children\":[]},{\"level\":3,\"title\":\"引用可达法\",\"slug\":\"引用可达法\",\"link\":\"#引用可达法\",\"children\":[]}]},{\"level\":2,\"title\":\"通用的分代垃圾回收机制\",\"slug\":\"通用的分代垃圾回收机制\",\"link\":\"#通用的分代垃圾回收机制\",\"children\":[{\"level\":3,\"title\":\"年轻代\",\"slug\":\"年轻代\",\"link\":\"#年轻代\",\"children\":[]},{\"level\":3,\"title\":\"年老代\",\"slug\":\"年老代\",\"link\":\"#年老代\",\"children\":[]},{\"level\":3,\"title\":\"持久代\",\"slug\":\"持久代\",\"link\":\"#持久代\",\"children\":[]}]},{\"level\":2,\"title\":\"其他注意事项\",\"slug\":\"其他注意事项\",\"link\":\"#其他注意事项\",\"children\":[]}],\"filePathRelative\":\"Program/后端/Java/JavaSE基础/面向对象概念/垃圾回收机制.md\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
