export const data = JSON.parse("{\"key\":\"v-6b3d80a8\",\"path\":\"/Program/%E5%89%8D%E7%AB%AF/Vue.js/%E7%9F%A5%E8%AF%86%E7%82%B9/vue-router/%E7%94%A8%E6%B3%95.html\",\"title\":\"用法\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"用法\",\"order\":10,\"description\":\"vue-router CDN ```html ``` 快速开始 ```html home Subpage const Home = { template: '首页' } const News = { template: '子页' } var router = new VueRouter({ // mode: 'hash', mode: 'history...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://mahe666.github.io/doc/Program/%E5%89%8D%E7%AB%AF/Vue.js/%E7%9F%A5%E8%AF%86%E7%82%B9/vue-router/%E7%94%A8%E6%B3%95.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"Mahe666\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"用法\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"vue-router CDN ```html ``` 快速开始 ```html home Subpage const Home = { template: '首页' } const News = { template: '子页' } var router = new VueRouter({ // mode: 'hash', mode: 'history...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"Mahe666\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"用法\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"Mahe666\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"vue-router CDN\",\"slug\":\"vue-router-cdn\",\"link\":\"#vue-router-cdn\",\"children\":[]},{\"level\":2,\"title\":\"快速开始\",\"slug\":\"快速开始\",\"link\":\"#快速开始\",\"children\":[{\"level\":3,\"title\":\"vue-router 示例\",\"slug\":\"vue-router-示例\",\"link\":\"#vue-router-示例\",\"children\":[]}]},{\"level\":2,\"title\":\"路由嵌套\",\"slug\":\"路由嵌套\",\"link\":\"#路由嵌套\",\"children\":[{\"level\":3,\"title\":\"代码示例\",\"slug\":\"代码示例\",\"link\":\"#代码示例\",\"children\":[]}]},{\"level\":2,\"title\":\"重定向\",\"slug\":\"重定向\",\"link\":\"#重定向\",\"children\":[]},{\"level\":2,\"title\":\"传递参数\",\"slug\":\"传递参数\",\"link\":\"#传递参数\",\"children\":[]},{\"level\":2,\"title\":\"编程式路由\",\"slug\":\"编程式路由\",\"link\":\"#编程式路由\",\"children\":[{\"level\":3,\"title\":\"利用JS实现路由跳转\",\"slug\":\"利用js实现路由跳转\",\"link\":\"#利用js实现路由跳转\",\"children\":[]},{\"level\":3,\"title\":\"通过watch实现路由监听\",\"slug\":\"通过watch实现路由监听\",\"link\":\"#通过watch实现路由监听\",\"children\":[]},{\"level\":3,\"title\":\"导航守卫\",\"slug\":\"导航守卫\",\"link\":\"#导航守卫\",\"children\":[]}]},{\"level\":2,\"title\":\"路由模式\",\"slug\":\"路由模式\",\"link\":\"#路由模式\",\"children\":[]},{\"level\":2,\"title\":\"通配页\",\"slug\":\"通配页\",\"link\":\"#通配页\",\"children\":[]}],\"filePathRelative\":\"Program/前端/Vue.js/知识点/vue-router/用法.md\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
