export const data = JSON.parse("{\"key\":\"v-5da631b7\",\"path\":\"/Program/%E6%95%B0%E6%8D%AE%E5%BA%93/RDBMS/KingBaseES/\",\"title\":\"KingBaseES\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"KingBaseES\",\"description\":\"人大金仓 官网： 下载地址： SpringBoot整合人大金仓 相关博客： 这个数据库底层是PostgreSQL 资源下载 安装包 下载地址： 安装时建议使用oracle模式，大小写不敏感 不允许密码为空，建议密码为123456，好记。。 仅远程连接时 远程连接数据库的时候直接选择客户端安装就好，这样就不需要证书了 授权文件 下载地址： 接口驱动 下载...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://mahe666.github.io/doc/Program/%E6%95%B0%E6%8D%AE%E5%BA%93/RDBMS/KingBaseES/\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"Mahe666\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"KingBaseES\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"人大金仓 官网： 下载地址： SpringBoot整合人大金仓 相关博客： 这个数据库底层是PostgreSQL 资源下载 安装包 下载地址： 安装时建议使用oracle模式，大小写不敏感 不允许密码为空，建议密码为123456，好记。。 仅远程连接时 远程连接数据库的时候直接选择客户端安装就好，这样就不需要证书了 授权文件 下载地址： 接口驱动 下载...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"Mahe666\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"KingBaseES\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"Mahe666\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"资源下载\",\"slug\":\"资源下载\",\"link\":\"#资源下载\",\"children\":[{\"level\":3,\"title\":\"安装包\",\"slug\":\"安装包\",\"link\":\"#安装包\",\"children\":[]},{\"level\":3,\"title\":\"授权文件\",\"slug\":\"授权文件\",\"link\":\"#授权文件\",\"children\":[]},{\"level\":3,\"title\":\"接口驱动\",\"slug\":\"接口驱动\",\"link\":\"#接口驱动\",\"children\":[]},{\"level\":3,\"title\":\"技术文档\",\"slug\":\"技术文档\",\"link\":\"#技术文档\",\"children\":[]}]},{\"level\":2,\"title\":\"项目错误笔记\",\"slug\":\"项目错误笔记\",\"link\":\"#项目错误笔记\",\"children\":[{\"level\":3,\"title\":\"The authentication type 10 is not supported. Check that you have configured the sys_hba.conf file to include the client's IP address or subnet, and that it is using an authentication scheme supported by the driver.\",\"slug\":\"the-authentication-type-10-is-not-supported-check-that-you-have-configured-the-sys-hba-conf-file-to-include-the-client-s-ip-address-or-subnet-and-that-it-is-using-an-authentication-scheme-supported-by-the-driver\",\"link\":\"#the-authentication-type-10-is-not-supported-check-that-you-have-configured-the-sys-hba-conf-file-to-include-the-client-s-ip-address-or-subnet-and-that-it-is-using-an-authentication-scheme-supported-by-the-driver\",\"children\":[]}]}],\"filePathRelative\":\"Program/数据库/RDBMS/KingBaseES/README.md\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
